digitization_subject:
  edmonton: http://id.loc.gov/authorities/names/n79007225
  edmonton_folk_music_festival: http://viaf.org/viaf/148861489
  folk_music_festivals: http://id.loc.gov/authorities/subjects/sh2008004058
  